on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "channel.yaml"
      - "install.sh"
      - "!.github/workflows/test-suite.yaml"

name: PR Build
permissions:
    contents: read
jobs:
  build-amd64:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Dapper
      run: |
        curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
        chmod +x /usr/local/bin/dapper
    - name: Build
      run: make ci
    - name: Test
      run: make test
    - name: Prepare Test Logs on Failure
      if: ${{ failure() }}
      run: |
        sudo cp -r /tmp/rke2-logs ~/rke2-logs
        sudo chown -R $USER:$USER ~/rke2-logs
        ls -la ~/rke2-logs
    - name: Upload Logs on Failure
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: rke2-test-logs
        path: ~/rke2-logs/
  build-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Dapper
      run: |
        curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
        chmod +x /usr/local/bin/dapper
    - name: Build
      run: make ci
        