name: Sync Images

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

env:
  GITHUB_ACTION_TAG: ${{ inputs.tag }}

permissions:
  contents: read
  id-token: write

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.tag }}

    - name: Install crane
      uses: ./.github/actions/install-crane
  
    - name: Build Images
      run: |
        dapper -f Dockerfile --target dapper make package-images

    # - name: Read secrets
    #   uses: rancher-eio/read-vault-secrets@main
    #   with:
    #     secrets: |
    #       secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry | PRIME_REGISTRY ;
    #       secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials username | PRIME_REGISTRY_USERNAME ;
    #       secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials password | PRIME_REGISTRY_PASSWORD

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ${{ env.PRIME_REGISTRY }}
    #     username: ${{ env.PRIME_REGISTRY_USERNAME }}
    #     password: ${{ env.PRIME_REGISTRY_PASSWORD }}

    - name: Sync images
      run: |
        ./scripts/copy-images.sh -d -t ${{ env.PRIME_REGISTRY }} -i dist/artifacts/rke2-images-all.linux-amd64.txt 
